version: '3.1'
services:
  database:
    image: postgres:10.3-alpine
    container_name: library_db
    restart: always
    hostname: 127.0.0.1
    volumes:
      - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      -  "5432:5432"
    environment:
      - POSTGRES_DB=librarydb
      - POSTGRES_USER=openlib
      - POSTGRES_PASSWORD=openlibco
  web-service:
    image: shinyay/docker-glassfish5
    container_name: library_web_service
    restart: always
    hostname: 127.0.0.1
    volumes:
      - ./webservice/Openlibrary-Webservice.war:/glassfish5/glassfish/domains/domain1/autodeploy/Openlibrary-Webservice.war
    ports:
      - 4848:4848
      - 8080:8080
      - 8181:8181
  web-application:
    image: shinyay/docker-glassfish5
    container_name: library_web_application
    hostname: 127.0.0.1
    volumes:
      - ./webapp/Openlibrary-Client.war:/glassfish5/glassfish/domains/domain1/autodeploy/Openlibrary-Client.war
      - ./webapp/logs:/glassfish5/glassfish/domains/domain1/logs
    ports:
      - 4949:4848
      - 80:8080
      - 8282:8181
  batch:
    image: mahxwell/library_batch
    container_name: library_batch
    volumes:
      - ./batchapp/logs:/logs